security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        my_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: login
                
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
