<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOrfbilb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOrfbilb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOrfbilb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOrfbilb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOrfbilb\appProdProjectContainer(array(
    'container.build_hash' => 'Orfbilb',
    'container.build_id' => '8a574f9b',
    'container.build_time' => 1527103833,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOrfbilb');
