<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2ydlqj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2ydlqj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ2ydlqj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQ2ydlqj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQ2ydlqj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Q2ydlqj',
    'container.build_id' => 'c1d7f525',
    'container.build_time' => 1529098324,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2ydlqj');
